sudo: false
language: node_js
node_js:
- 6.9.0
before_script:
- gem install scss_lint -v 0.49.0
- gem install compass
script:
- npm run build
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || travis_terminate 0'
- 'npm run coverage && codeclimate-test-reporter < ./coverage/lcov.info'
notifications:
  slack:
    secure: KxP+fsA7PMmmoS+/F+8Sg0U7EZR0C2y4/QK4PL5XvgYqjesqWhA6VXBfh+UC3QjXozLEHHgIcknYpypnTHoR/yHISDS2yUj9rcYhuwa1qTYzuTuFrgWAAAXUVfe0tuCLqMIAOprUMAzKCkExpimgTbotiSbH25ZsPof4iDB8e3ItSO1dJ9khakFswCBCzrBeBMZBKByANBlk2NvKvZnsnem+gjcRgHwDROfIgeqWhZxlgrULHkRGaAS1+/7UzHg6fM5VzB3e8s+v+AVOU+Td89M2M75ec2PtE0rxPzpJzTszUR4qGFpa3ofWXc4h0pVMTx6iwklTEw+W84FiFKI2ce2nhMzavJplvM/YNvaj7t/LGd6rR+Vqp3wOb5WHaZ6dvul8388PCk7OEKynN9tZe0KdgfA5T2cCL7SvJwwygmmnbWc7acUBYivl9wOFE6gY/QNXZ7jtMKbagrDQsggMP2aVQNrAsLkXHAm0JhZRjOfaaERrFLhaXHzlJEzJ4vClDVzBiBw0XzYKkjHCK6d9ZEtZNhM5GIA0sbf39HMtM3+blllpgOakY+/NgvTtDymCLcxNj4TfQDEPnJV8oMzT5pm9Av1fv79z9b3T4bUKkOJa7pQo1y281sL98MyRwOqtSxPJpsFodZFAKJJGTKerQA+1d6+d/KY/8DAh1v491js=
env:
  global:
    secure: VwesyyyQuGgyjXYktKZW6YLa/OZnhnxw3LtrboshRC/5sc/TLtvN4QbIewUnN6wsczpBhwQXqGTBmDGr2fZx2oj7BEN5yhTpsE1YBmKU9t+YW2o0IsIpWIMfAmryHMieF8qNb8uSQQRcDMkEtgIlmvy8EEsZm1wfJy6jfKHtkxfJHPkvfwj+gvvKKz+6WK/JHQrmhlU5W5AdJfY5H6ZGbLpr2Km1fNb4DY/9T/gHwBHDHOsodPS786E6KWjBaefORIkgvHzWOVXV/hTQmPU14PuBEVjbGDyr09oNmqr6VcNuui963f6Osux8NlkVzG2f/boEmHKf2DLIay+LpLAv/IWHBE2b8bLdlYNpWZpw04V8cSxN4xJag444CRQRZbWPbp2nEJF3yYv+lCyHIp0SZpJj2ZTypLY7KfNFpsm7ZVBDeSf9Wcqk2Yuz5JZ7A3y+flCO3EgBlvFEMBM6/Xn9l9/FNLOohso1+UxnzGyPzDBfgHi08clN29KuEFz4Bu7elompGHNipw9co1284H00R0m3p8CZVMhEKZONYPo0R6cplZAShkqjnD2DivPIHS4+nzdOLNWrJmPt4orRx8zY7gYo42XBWvqljefViJVGtVvnysX6pUxvh4Ie8JLeNBxGdKuKypAe85Wk2Ak6m2cB2ZLu3ZARLpuYeETq5iazqBA=
before_deploy:
- npm run build
deploy:
  provider: npm
  email: mark@dhis2.org
  api_key:
    secure: E4v33CS/hPzXQjZHjzmzU1CpW/eyrA4RopXR7/f9cRNpIHOITTQsRvBtgbJ9cCAZ37PbVqzlGeI7QV6M6DZrMV4CyVple9zQwn8UocKYTxHxIr/qZj2UxrppGcj2+967zgDQXqQm6/rD2IvIDQaPj9UUXd5ohAEOzmkbIZ4VYTgbQit7/lTPIl9fWThlNVuAbZE+Lco41wBhzQeAsr+BFqQTm2L3gDnvZo0B2HvOIkukJQD0SdxFZ+nYtjoE0G8c8fJQ0AmTcsUiS7+Y+4mmQl5nz4Ma2YxHelxHJTl6cnRUg4g7ZZR2qSGJHhFgwT5fu23XelxX/CXRL9M48lO5kQhqufojQyAQiVHWjhucnt83KlpoAX7AC913GZabHBJXEasQtdhZlmzQaER47I0FnlwcL14gVsB4N1rFRNWKEowYyV/VLtVNJvdb/CTl4zFZOc/DoFIEsQxkB0l+/t+59DrXaxN9+0UXiY60T9r4Lp9pwWVGz/9oJn7NCbjWEEXmw7QjgT/QOzBap0/1Nb3jcE2MmKFl7Di1HBhr/YUOeN+tR/IH6Q6Bteu2612fqZVVWBZAhtMnNdKN1XbfDBOughzDzsBgZyz+wOptsG/Ud79EMQlZ1hvz8NzBZ3P3I+4c3JyV78ahPAZxSgwOjSnJn2N90hV2EgSUFzddxnNCZpY=
  on:
    tags: true
    repo: dhis2/d2-ui
