sudo: false
language: node_js
node_js:
- 6.9.0
before_script:
- gem install scss_lint -v 0.49.0
- gem install compass normalize-scss breakpoint susy
script:
- npm run build
- npm run coverage
notifications:
  slack:
    secure: KxP+fsA7PMmmoS+/F+8Sg0U7EZR0C2y4/QK4PL5XvgYqjesqWhA6VXBfh+UC3QjXozLEHHgIcknYpypnTHoR/yHISDS2yUj9rcYhuwa1qTYzuTuFrgWAAAXUVfe0tuCLqMIAOprUMAzKCkExpimgTbotiSbH25ZsPof4iDB8e3ItSO1dJ9khakFswCBCzrBeBMZBKByANBlk2NvKvZnsnem+gjcRgHwDROfIgeqWhZxlgrULHkRGaAS1+/7UzHg6fM5VzB3e8s+v+AVOU+Td89M2M75ec2PtE0rxPzpJzTszUR4qGFpa3ofWXc4h0pVMTx6iwklTEw+W84FiFKI2ce2nhMzavJplvM/YNvaj7t/LGd6rR+Vqp3wOb5WHaZ6dvul8388PCk7OEKynN9tZe0KdgfA5T2cCL7SvJwwygmmnbWc7acUBYivl9wOFE6gY/QNXZ7jtMKbagrDQsggMP2aVQNrAsLkXHAm0JhZRjOfaaERrFLhaXHzlJEzJ4vClDVzBiBw0XzYKkjHCK6d9ZEtZNhM5GIA0sbf39HMtM3+blllpgOakY+/NgvTtDymCLcxNj4TfQDEPnJV8oMzT5pm9Av1fv79z9b3T4bUKkOJa7pQo1y281sL98MyRwOqtSxPJpsFodZFAKJJGTKerQA+1d6+d/KY/8DAh1v491js=
env:
  global:
    secure: VwesyyyQuGgyjXYktKZW6YLa/OZnhnxw3LtrboshRC/5sc/TLtvN4QbIewUnN6wsczpBhwQXqGTBmDGr2fZx2oj7BEN5yhTpsE1YBmKU9t+YW2o0IsIpWIMfAmryHMieF8qNb8uSQQRcDMkEtgIlmvy8EEsZm1wfJy6jfKHtkxfJHPkvfwj+gvvKKz+6WK/JHQrmhlU5W5AdJfY5H6ZGbLpr2Km1fNb4DY/9T/gHwBHDHOsodPS786E6KWjBaefORIkgvHzWOVXV/hTQmPU14PuBEVjbGDyr09oNmqr6VcNuui963f6Osux8NlkVzG2f/boEmHKf2DLIay+LpLAv/IWHBE2b8bLdlYNpWZpw04V8cSxN4xJag444CRQRZbWPbp2nEJF3yYv+lCyHIp0SZpJj2ZTypLY7KfNFpsm7ZVBDeSf9Wcqk2Yuz5JZ7A3y+flCO3EgBlvFEMBM6/Xn9l9/FNLOohso1+UxnzGyPzDBfgHi08clN29KuEFz4Bu7elompGHNipw9co1284H00R0m3p8CZVMhEKZONYPo0R6cplZAShkqjnD2DivPIHS4+nzdOLNWrJmPt4orRx8zY7gYo42XBWvqljefViJVGtVvnysX6pUxvh4Ie8JLeNBxGdKuKypAe85Wk2Ak6m2cB2ZLu3ZARLpuYeETq5iazqBA=
before_deploy:
- npm run build
deploy:
  provider: npm
  email: deployment@dhis2.org
  skip_cleanup: true
  api_key:
    secure: H3rbaRsqEnoiDZ+mZ8qSzHAsxpT8YqOHj+uhs9BafXluLQWZKvGVn+lqLAK+mrS3WK+GOtPT76wJYw+gr7i2i0jxrsNt4kov6GeHzmkKkVEQaejOgqV3UZl0f4VAXzATjbvBgdbcQPSqPbPruj3cCywfvzfIJdAB5sYd8Vb4uevA/GaquvzTsNLU/Wvxx8GTt5hGhqf6+V7jWgV3zDz/udO1KmHzDaZu719U3fkv9vW8KQKXp0Jld/a6u5r4pBcObfUVld+tgLPMj/4XDGqK9nZyauJQPkr8UohcIU6krf19aXWcCxdwwQNlBspbnRtLVj5mkIgDNjli45/229alxVJ94aYAQgysMMvMinAoheSnv3ANQhMDxNZmSa6y53r3enRkeF2iQDR0xxnjk1Gp242JGxl9J8QBON1na0Eh+0UL+aIq3CTc2Dx+svEJWIUMPdprNnSYXzou4TsPn04sJaDKIvFHOPmy+g3EOOslKBvCLAjCBQLCbTsBQLU7WZI0nL2raypQGlwTinSfsxwlgYYkX1QjaLmpodXzNPoU1B2kw5MIr1FTZPbb+sjCjV6nSW7WotngCqGEmr8hjbo59/1PY4PqaaXJFjxlrDMzdCu6ZkA5lbHW+pB+rRQ8mhYZPequfDL2geaNhF5hp9bDsEbiGZLA6A8KQxbmhyxnWcM=
  on:
    tags: true
    repo: dhis2/d2-ui
